ALTER TABLE "public_pages"
ADD COLUMN IF NOT EXISTS "accent_color" VARCHAR(20),
ADD COLUMN IF NOT EXISTS "font_family" VARCHAR(40),
ADD COLUMN IF NOT EXISTS "title_size" VARCHAR(20),
ADD COLUMN IF NOT EXISTS "title_align" VARCHAR(20),
ADD COLUMN IF NOT EXISTS "body_size" VARCHAR(20),
ADD COLUMN IF NOT EXISTS "layout_variant" VARCHAR(40);
